lib: hide static functions that are never defined
Arch-specific functions not defined for all architectures (missing on x86 in
this case) and not used anywhere should not expose a prototype.

This commit prevents the following errors:

 error: `rte_mov48' declared `static' but never defined
 error: `rte_memcpy_func' declared `static' but never defined

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>